### ISSUE TITLE
GooglePodcasts App cant find the podcast

### ISSUE THREAD

**Issue by madawei2699** [microfeed/microfeed#100]
How to let the GooglePodcasts App can find the podcast?

**Comment by wenbinf** [comment]
You'll have to submit the rss feed to Google Podcasts first.

Please learn more here on Google's website: https://support.google.com/podcast-publishers/answer/10315648?hl=en

**Comment by wenbinf** [comment]
Turns out for Google Podcasts, you'll just need to wait until it's indexed: https://support.google.com/podcast-publishers/answer/9890138?ref_topic=10308237&sjid=7616317664168796954-AP

Or you can ask Google Search Console to index the homepage:
<img width="731" alt="Screenshot 2023-09-26 at 7 42 15 PM" src="https://github.com/microfeed/microfeed/assets/1719237/8486ead1-f276-4071-88d4-bc5c6816f426">

**Comment by wenbinf** [comment]
Also read this: https://support.google.com/podcast-publishers/answer/9479755?sjid=7616317664168796954-AP#zippy=%2Cadd-a-show

**Comment by madawei2699** [comment]
Thanks @wenbinf but when I submit the URL to [google podcast](https://podcastsmanager.google.com/add-feed?hl=en), it shows an error: This feed is missing an email address. Add an email address to your RSS feed.
So it seems the microfeed needs to allow setting the email address?

**Comment by wenbinf** [comment]
Yes, you can easily set email address on microfeed admin - 

/admin/channels/primary/ (scroll down)
<img width="1055" alt="Screenshot 2023-09-26 at 8 32 03 PM" src="https://github.com/microfeed/microfeed/assets/1719237/2cf99a31-bf34-4290-b26e-591e4508d52f">

**Comment by madawei2699** [comment]
That's awesome, thanks!
