### ISSUE TITLE
CORS errors and 403 Forbidden's

### ISSUE THREAD

**Issue by philholden** [microfeed/microfeed#45]
I think the first time I uploaded an image I saw it in the UI but now I just get a broken image icon

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1674806/213880910-50121c4c-3f92-4e3c-b585-082097649040.png">

It looks like I am getting CORS errors. If I try to load the image directly in a new tab then it will load.

But after a couple of refreshes in another tab I get 403 Forbidden (I think this is some kind of rate limiting because if I then try to load the image on my phone it works).

I am accessing through a custom domain so I was not expecting rate limiting.

Any idea how I fix the CORS error as I did not see a step to allow-origin: "*" on:

cdn.mysite.com

**Comment by wenbinf** [comment]
@philholden 

CORS settings should be taken care of during the deployment process. This is from your GitHub Actions:
https://github.com/philholden/microfeed/actions/runs/3973909543/jobs/6812854381

<img width="722" alt="Screenshot 2023-01-21 at 10 23 14 AM" src="https://user-images.githubusercontent.com/1719237/213881511-44a45073-20c9-42c9-ac4f-84b5291ff60d.png">

Are you able to directly access an image from your R2's public url? You may want to double check if you provide a correct R2 bucket's url.

You can open browser's developer console to see the full url of an image.

**Comment by philholden** [comment]
I can access it from:

https://cdn.example.org/microfeed-sfp/production/media/image-ade6c188d0b75a674e6ed05f08000326.png

Provided I open in a new tab. It just is not working when loaded cross
origin in the context of the cms.

**Comment by wenbinf** [comment]
could you take a screenshot of your browser's developer console? it would be helpful to see the error message. otherwise, it's tricky to debug via textual description :) 

for security reasons, you might mail the screenshot to support@microfeed.org, rather than posting here to the public.

we can come back here to update what went wrong without revealing the real url.

**Comment by wenbinf** [comment]
Closed this issue now.

In case someone comes from Google search and had similar issue in the future, here are some updates - 

Chatted w/ @philholden via email, and the issue was resolved automatically (i.e., close Chrome, refresh the page...). 
From the symptoms, I guess this is what happened - after setting up a custom domain for R2 public bucket, there was some delay for DNS to propagate. so it took a few minutes for R2 assets to be accessible via custom domain.
